name: Java CI with Gradle

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: test
            os: ubuntu-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3

      - name: Make Gradle Script Executable
        run: chmod +x ${{github.workspace}}/gradlew

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@ce999babab2de1c4b649dc15f0ee67e6246c994f
        with:
          arguments: ${{ matrix.target }}